#!/usr/bin/env bash
# This script prints numbers from 1 to 100 with FizzBuzz logic

i=1
while [ "$i" -le 100 ]; do
  if [ $((i % 15)) -eq 0 ]; then
    printf "FizzBuzz\n"
  elif [ $((i % 3)) -eq 0 ]; then
    printf "Fizz\n"
  elif [ $((i % 5)) -eq 0 ]; then
    printf "Buzz\n"
  else
    printf "%s\n" "$i"
  fi
  i=$((i + 1))
done
