#!/usr/bin/env bash
# This script displays username, user id and home directory from /etc/passwd

while IFS=':' read -r username _ userid _ _ home _; do
    printf "%s:%s:%s\n" "$username" "$userid" "$home"
done < /etc/passwd
