#!/usr/bin/env bash
# This script displays "Best School" 10 times, but on the 9th iteration also prints "Hi"
i=1
while [ "$i" -le 10 ]
do
  if [ "$i" -eq 9 ]
  then
    printf "%s\n%s\n" "Best School" "Hi"
  else
    printf "%s\n" "Best School"
  fi
  i=$((i+1))
done
