#!/usr/bin/env bash
# This script loops from 1 to 10 and prints different messages for the 4th and 8th iterations
i=1
while [ "$i" -le 10 ]
do
  if [ "$i" -eq 4 ]
  then
    printf "%s\n" "bad luck"
  elif [ "$i" -eq 8 ]
  then
    printf "%s\n" "good luck"
  else
    printf "%s\n" "Best School"
  fi
  i=$((i+1))
done
