#!/usr/bin/env bash
# This script displays hours (0–12) and minutes (1–59) using while loops

hour=0

while [ "$hour" -le 12 ]
do
  printf "Hour: %s\n" "$hour"

  minute=1
  while [ "$minute" -le 59 ]
  do
    printf "%s\n" "$minute"
    minute=$((minute + 1))
  done

  hour=$((hour + 1))
done
